# Generated by Django 6.0.6 on 2026-06-26 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_access_point',
            fields=[
                ('access_id', models.AutoField(primary_key=True, serialize=False)),
                ('access_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tbl_access_point',
            },
        ),
        migrations.CreateModel(
            name='tbl_cmf_add_info',
            fields=[
                ('info_no', models.AutoField(primary_key=True, serialize=False)),
                ('information_details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_cmf_add_info',
            },
        ),
        migrations.CreateModel(
            name='tbl_cmf_color_req',
            fields=[
                ('color_req_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_cmf_color_req',
            },
        ),
        migrations.CreateModel(
            name='tbl_cmf_pending_completed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cm_no', models.CharField(blank=True, max_length=50, null=True)),
                ('matching_type', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('prod_code', models.CharField(blank=True, max_length=100, null=True)),
                ('code_details', models.TextField(blank=True, null=True)),
                ('date_submitted', models.DateField(blank=True, null=True)),
                ('ar_no', models.CharField(blank=True, max_length=50, null=True)),
                ('ar_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tbl_cmf_pending_completed',
            },
        ),
        migrations.CreateModel(
            name='tbl_cmf_process',
            fields=[
                ('process_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_cmf_process',
            },
        ),
        migrations.CreateModel(
            name='tbl_cmf_salesman',
            fields=[
                ('sm_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_cmf_salesman',
            },
        ),
        migrations.CreateModel(
            name='tbl_cmf_specification',
            fields=[
                ('spec_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_cmf_specification',
            },
        ),
        migrations.CreateModel(
            name='tbl_feedback_details',
            fields=[
                ('feedback_no', models.AutoField(primary_key=True, serialize=False)),
                ('rm_feedback_no', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('storage_details', models.CharField(blank=True, max_length=100, null=True)),
                ('cm_rs_no', models.CharField(blank=True, max_length=14, null=True)),
            ],
            options={
                'db_table': 'tbl_feedback_details',
            },
        ),
        migrations.CreateModel(
            name='tbl_formula01',
            fields=[
                ('form_id', models.AutoField(primary_key=True, serialize=False)),
                ('index_no', models.CharField(blank=True, max_length=22, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('customer', models.CharField(blank=True, max_length=62, null=True)),
                ('prod_code', models.CharField(max_length=22)),
                ('prod_color', models.CharField(blank=True, max_length=62, null=True)),
                ('dosage', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('total_concentration', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('ld', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('mix_time', models.CharField(blank=True, max_length=22, null=True)),
                ('resin', models.CharField(blank=True, max_length=36, null=True)),
                ('application', models.CharField(blank=True, max_length=36, null=True)),
                ('colormatch_no', models.CharField(blank=True, max_length=8, null=True)),
                ('colormatch_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=256, null=True)),
                ('date_time', models.CharField(blank=True, max_length=32, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tbl_formula01',
            },
        ),
        migrations.CreateModel(
            name='tbl_generated_prod_code',
            fields=[
                ('code_no', models.AutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'tbl_generated_prod_code',
            },
        ),
        migrations.CreateModel(
            name='tbl_internal_color_code',
            fields=[
                ('in_code_no', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'tbl_internal_color_code',
            },
        ),
        migrations.CreateModel(
            name='tbl_production01',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_date', models.DateField(blank=True, null=True)),
                ('customer', models.CharField(blank=True, max_length=62, null=True)),
                ('form_id', models.IntegerField(blank=True, null=True)),
                ('index_no', models.CharField(blank=True, max_length=32, null=True)),
                ('prod_code', models.CharField(blank=True, max_length=32, null=True)),
                ('prod_color', models.CharField(blank=True, max_length=62, null=True)),
                ('dosage', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('ld', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('lot_no', models.CharField(blank=True, max_length=128, null=True)),
                ('order_no', models.CharField(blank=True, max_length=36, null=True)),
                ('colormatch_no', models.CharField(blank=True, max_length=8, null=True)),
                ('colormatch_date', models.DateField(blank=True, null=True)),
                ('mix_time', models.CharField(blank=True, max_length=32, null=True)),
                ('machine_no', models.CharField(blank=True, max_length=32, null=True)),
                ('note', models.CharField(blank=True, max_length=128, null=True)),
                ('user_id', models.CharField(blank=True, max_length=62, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_printed', models.BooleanField(default=False)),
                ('inventory_c_date', models.DateField(blank=True, null=True)),
                ('form_type', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'tbl_production01',
            },
        ),
        migrations.CreateModel(
            name='tbl_raw_material_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rm_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'tbl_raw_material_list',
            },
        ),
        migrations.CreateModel(
            name='tbl_rm_incoming',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('material_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_rm_incoming',
            },
        ),
        migrations.CreateModel(
            name='tbl_cmf',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cm_no', models.CharField(max_length=50, unique=True)),
                ('matching_type', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_color', models.CharField(blank=True, max_length=100, null=True)),
                ('color_desc', models.TextField(blank=True, null=True)),
                ('qty_resin_testing', models.CharField(blank=True, max_length=100, null=True)),
                ('is_resin_provided', models.BooleanField(blank=True, null=True)),
                ('mi_c_resin', models.CharField(blank=True, max_length=100, null=True)),
                ('is_sample_available', models.BooleanField(blank=True, null=True)),
                ('colorant_type', models.CharField(blank=True, max_length=100, null=True)),
                ('is_guide_to_return', models.BooleanField(blank=True, null=True)),
                ('temperature', models.CharField(blank=True, max_length=50, null=True)),
                ('is_low_cost', models.BooleanField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('info', models.ForeignKey(blank=True, db_column='info_no', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tbl_cmf_add_info')),
                ('sm', models.ForeignKey(blank=True, db_column='sm_no', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tbl_cmf_salesman')),
            ],
            options={
                'db_table': 'tbl_cmf',
            },
        ),
        migrations.CreateModel(
            name='tbl_cmf_dates',
            fields=[
                ('cm_dates_no', models.AutoField(primary_key=True, serialize=False)),
                ('form_made', models.DateField(blank=True, null=True)),
                ('date_required', models.CharField(blank=True, max_length=36, null=True)),
                ('date_received_lab', models.CharField(blank=True, max_length=36, null=True)),
                ('due_date_lab', models.DateField(blank=True, null=True)),
                ('cm', models.ForeignKey(db_column='cm_no', on_delete=django.db.models.deletion.CASCADE, to='main.tbl_cmf', to_field='cm_no')),
            ],
            options={
                'db_table': 'tbl_cmf_dates',
            },
        ),
        migrations.CreateModel(
            name='tbl_cmf_formula',
            fields=[
                ('cmf_formula_no', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.CharField(blank=True, max_length=150, null=True)),
                ('finished_product', models.CharField(blank=True, max_length=150, null=True)),
                ('resin', models.CharField(blank=True, max_length=100, null=True)),
                ('dosage', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('cm', models.ForeignKey(db_column='cm_no', on_delete=django.db.models.deletion.CASCADE, to='main.tbl_cmf', to_field='cm_no')),
            ],
            options={
                'db_table': 'tbl_cmf_formula',
            },
        ),
        migrations.CreateModel(
            name='tbl_cmf_process02',
            fields=[
                ('chosen_process_no', models.AutoField(primary_key=True, serialize=False)),
                ('cmf_formula', models.ForeignKey(db_column='cmf_formula_no', on_delete=django.db.models.deletion.CASCADE, to='main.tbl_cmf_formula')),
                ('process', models.ForeignKey(blank=True, db_column='process_no', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tbl_cmf_process')),
            ],
            options={
                'db_table': 'tbl_cmf_process02',
            },
        ),
        migrations.CreateModel(
            name='tbl_cmf_specification02',
            fields=[
                ('chosen_spec_no', models.AutoField(primary_key=True, serialize=False)),
                ('cm', models.ForeignKey(db_column='cm_no', on_delete=django.db.models.deletion.CASCADE, to='main.tbl_cmf', to_field='cm_no')),
                ('spec', models.ForeignKey(blank=True, db_column='spec_no', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tbl_cmf_specification')),
            ],
            options={
                'db_table': 'tbl_cmf_specification02',
            },
        ),
        migrations.CreateModel(
            name='tbl_dc_extruder_formula',
            fields=[
                ('dc_no', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('sample_size', models.CharField(blank=True, max_length=100, null=True)),
                ('mixing_time', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('matched_by', models.CharField(blank=True, max_length=100, null=True)),
                ('weighted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('encoded_by', models.CharField(blank=True, max_length=100, null=True)),
                ('total_weight', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('cm', models.ForeignKey(blank=True, db_column='cm_no', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tbl_cmf', to_field='cm_no')),
                ('code', models.ForeignKey(blank=True, db_column='code_no', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tbl_generated_prod_code')),
            ],
            options={
                'db_table': 'tbl_dc_extruder_formula',
            },
        ),
        migrations.CreateModel(
            name='tbl_dc_extruder_formula02',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('material', models.CharField(blank=True, max_length=150, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('dc', models.ForeignKey(db_column='dc_no', on_delete=django.db.models.deletion.CASCADE, to='main.tbl_dc_extruder_formula')),
            ],
            options={
                'db_table': 'tbl_dc_extruder_formula02',
            },
        ),
        migrations.CreateModel(
            name='tbl_formula02',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sequence_no', models.IntegerField(blank=True, null=True)),
                ('material_code', models.CharField(blank=True, max_length=32, null=True)),
                ('concentration', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('form', models.ForeignKey(db_column='form_id', on_delete=django.db.models.deletion.CASCADE, to='main.tbl_formula01')),
            ],
            options={
                'db_table': 'tbl_formula02',
            },
        ),
        migrations.CreateModel(
            name='tbl_formula_encode',
            fields=[
                ('encode_id', models.AutoField(primary_key=True, serialize=False)),
                ('match_by', models.CharField(blank=True, max_length=128, null=True)),
                ('encoded_by', models.CharField(blank=True, max_length=128, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True)),
                ('form', models.ForeignKey(db_column='form_id', on_delete=django.db.models.deletion.CASCADE, to='main.tbl_formula01')),
            ],
            options={
                'db_table': 'tbl_formula_encode',
            },
        ),
        migrations.AddField(
            model_name='tbl_generated_prod_code',
            name='in_code',
            field=models.ForeignKey(blank=True, db_column='in_code_no', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tbl_internal_color_code'),
        ),
        migrations.CreateModel(
            name='tbl_master_formula',
            fields=[
                ('form_id', models.AutoField(primary_key=True, serialize=False)),
                ('index_no', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('customer', models.CharField(blank=True, max_length=150, null=True)),
                ('prod_color', models.CharField(blank=True, max_length=150, null=True)),
                ('dosage', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('total_concentration', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('ld', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('mix_time', models.CharField(blank=True, max_length=100, null=True)),
                ('resin', models.CharField(blank=True, max_length=150, null=True)),
                ('application', models.CharField(blank=True, max_length=150, null=True)),
                ('cm_no', models.CharField(blank=True, max_length=50, null=True)),
                ('colormatch_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_used', models.BooleanField(default=False)),
                ('html_code_hex', models.CharField(blank=True, max_length=10, null=True)),
                ('cyan', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('magenta', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('yellow', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('black', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('product_code', models.ForeignKey(blank=True, db_column='product_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tbl_generated_prod_code', to_field='product_code')),
            ],
            options={
                'db_table': 'tbl_master_formula',
            },
        ),
        migrations.CreateModel(
            name='tbl_master_formula_encode',
            fields=[
                ('encode_id', models.AutoField(primary_key=True, serialize=False)),
                ('match_by', models.CharField(blank=True, max_length=100, null=True)),
                ('encoded_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('form', models.ForeignKey(db_column='form_id', on_delete=django.db.models.deletion.CASCADE, to='main.tbl_master_formula')),
            ],
            options={
                'db_table': 'tbl_master_formula_encode',
            },
        ),
        migrations.CreateModel(
            name='tbl_master_formula_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sequence_no', models.IntegerField(blank=True, null=True)),
                ('material_code', models.CharField(blank=True, max_length=100, null=True)),
                ('concentration', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('form', models.ForeignKey(db_column='form_id', on_delete=django.db.models.deletion.CASCADE, to='main.tbl_master_formula')),
            ],
            options={
                'db_table': 'tbl_master_formula_info',
            },
        ),
        migrations.CreateModel(
            name='tbl_mb_extruder_formula',
            fields=[
                ('mb_no', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('lot_no', models.CharField(blank=True, max_length=100, null=True)),
                ('mixing_time', models.CharField(blank=True, max_length=50, null=True)),
                ('matched_by', models.CharField(blank=True, max_length=100, null=True)),
                ('weighted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('encoded_by', models.CharField(blank=True, max_length=100, null=True)),
                ('total_weight', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('cm', models.ForeignKey(blank=True, db_column='cm_no', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tbl_cmf', to_field='cm_no')),
                ('code', models.ForeignKey(blank=True, db_column='code_no', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tbl_generated_prod_code')),
            ],
            options={
                'db_table': 'tbl_mb_extruder_formula',
            },
        ),
        migrations.CreateModel(
            name='tbl_mb_extruder_formula02',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('material', models.CharField(blank=True, max_length=150, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('mb', models.ForeignKey(db_column='mb_no', on_delete=django.db.models.deletion.CASCADE, to='main.tbl_mb_extruder_formula')),
            ],
            options={
                'db_table': 'tbl_mb_extruder_formula02',
            },
        ),
        migrations.CreateModel(
            name='tbl_production02',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sequence_no', models.IntegerField(blank=True, null=True)),
                ('material_code', models.CharField(blank=True, max_length=32, null=True)),
                ('large_scale', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('small_scale', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('total_weight', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('total_loss', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('total_consumption', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('prod', models.ForeignKey(db_column='prod_id', on_delete=django.db.models.deletion.CASCADE, to='main.tbl_production01')),
            ],
            options={
                'db_table': 'tbl_production02',
            },
        ),
        migrations.CreateModel(
            name='tbl_production_encode',
            fields=[
                ('encode_id', models.AutoField(primary_key=True, serialize=False)),
                ('prepared_by', models.CharField(blank=True, max_length=128, null=True)),
                ('encoded_by', models.CharField(blank=True, max_length=128, null=True)),
                ('encoded_on', models.DateTimeField(blank=True, null=True)),
                ('confirmation_encoded_on', models.DateTimeField(blank=True, null=True)),
                ('prod', models.ForeignKey(db_column='prod_id', on_delete=django.db.models.deletion.CASCADE, to='main.tbl_production01')),
            ],
            options={
                'db_table': 'tbl_production_encode',
            },
        ),
        migrations.CreateModel(
            name='tbl_production_quantity',
            fields=[
                ('quantity_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_req', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('quantity_batch', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('quantity_prod', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('prod', models.ForeignKey(db_column='prod_id', on_delete=django.db.models.deletion.CASCADE, to='main.tbl_production01')),
            ],
            options={
                'db_table': 'tbl_production_quantity',
            },
        ),
        migrations.CreateModel(
            name='tbl_role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_role',
                'unique_together': {('department', 'role')},
            },
        ),
        migrations.CreateModel(
            name='tbl_rs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rs_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('customer', models.CharField(blank=True, max_length=150, null=True)),
                ('pieces', models.IntegerField(blank=True, null=True)),
                ('quantity_given', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('date_form_made', models.DateField(blank=True, null=True)),
                ('date_lab_received', models.CharField(blank=True, max_length=36, null=True)),
                ('date_required', models.CharField(blank=True, max_length=36, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('color_description', models.TextField(blank=True, null=True)),
                ('finished_product', models.CharField(blank=True, max_length=150, null=True)),
                ('matching_type', models.CharField(blank=True, max_length=50, null=True)),
                ('lot_no', models.CharField(blank=True, max_length=100, null=True)),
                ('ar_no', models.CharField(blank=True, max_length=50, null=True)),
                ('date_sample_received', models.DateField(blank=True, null=True)),
                ('primary_color', models.CharField(blank=True, max_length=100, null=True)),
                ('color_desc', models.TextField(blank=True, null=True)),
                ('resin', models.CharField(blank=True, max_length=100, null=True)),
                ('chosen_process_no', models.IntegerField(blank=True, null=True)),
                ('colorant_type', models.CharField(blank=True, max_length=50, null=True)),
                ('date_submitted', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('cm', models.ForeignKey(blank=True, db_column='cm_no', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tbl_cmf', to_field='cm_no')),
            ],
            options={
                'db_table': 'tbl_rs',
            },
        ),
        migrations.CreateModel(
            name='tbl_rs_prod_codes',
            fields=[
                ('rs_code_no', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.ForeignKey(blank=True, db_column='code_no', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tbl_generated_prod_code')),
                ('rs', models.ForeignKey(blank=True, db_column='rs_no', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tbl_rs', to_field='rs_no')),
            ],
            options={
                'db_table': 'tbl_rs_prod_codes',
            },
        ),
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('role', models.ForeignKey(blank=True, db_column='role_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tbl_role')),
            ],
            options={
                'db_table': 'tbl_user',
            },
        ),
        migrations.AddField(
            model_name='tbl_rs',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tbl_user'),
        ),
        migrations.CreateModel(
            name='tbl_cmf_scanned',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('cm', models.ForeignKey(db_column='cm_no', on_delete=django.db.models.deletion.CASCADE, to='main.tbl_cmf', to_field='cm_no')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tbl_user')),
            ],
            options={
                'db_table': 'tbl_cmf_scanned',
            },
        ),
        migrations.AddField(
            model_name='tbl_cmf',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tbl_user'),
        ),
        migrations.CreateModel(
            name='tbl_audit_trail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(blank=True, max_length=50, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tbl_user')),
            ],
            options={
                'db_table': 'tbl_audit_trail',
            },
        ),
        migrations.CreateModel(
            name='tbl_role_permissions',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=False)),
                ('access', models.ForeignKey(db_column='access_id', on_delete=django.db.models.deletion.CASCADE, to='main.tbl_access_point')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='main.tbl_role')),
            ],
            options={
                'db_table': 'tbl_role_permissions',
                'unique_together': {('role', 'access')},
            },
        ),
    ]
