# Generated by Django 6.0.6 on 2026-06-26 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_cmf_color_req',
            name='cm',
            field=models.ForeignKey(blank=True, db_column='cm_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tbl_cmf', to_field='cm_no'),
        ),
    ]
