# Generated by Django 6.0.6 on 2026-09-04 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_tbl_master_formula_colorant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_feedback_details',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
