# Generated by Django 6.0.6 on 2026-09-10 05:26

from django.db import migrations

def add_new_access_points(apps, schema_editor):
    Role = apps.get_model('main', 'tbl_role')
    AccessPoint = apps.get_model('main', 'tbl_access_point')
    Permission = apps.get_model('main', 'tbl_role_permissions')

    new_access_list = [
        'Formula Records',
        'Master Formula',
        'Formulation',
    ]
    for name in new_access_list:
        AccessPoint.objects.get_or_create(access_name=name)

    # Make sure admin has all access points, old and new
    try:
        admin_role = Role.objects.get(department='Information Technology', role='ADMIN')
        for point in AccessPoint.objects.all():
            Permission.objects.get_or_create(
                role=admin_role,
                access=point,
                defaults={'is_enabled': True}
            )
    except Role.DoesNotExist:
        pass

def reverse_noop(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_tbl_password_reset_request'),
    ]

    operations = [
        migrations.RunPython(add_new_access_points, reverse_noop),
    ]
