# Generated by Django 6.0.6 on 2026-09-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_add_more_access_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_cmf_dates',
            name='submit_to_lab',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
