# Generated by Django 6.0.6 on 2026-09-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_tbl_cmf_dates_submit_to_lab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_cmf_pending_completed',
            name='reason',
            field=models.TextField(blank=True, default='Pending', null=True),
        ),
    ]
