# Generated by Django 6.0.6 on 2026-09-17 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_tbl_cmf_pending_completed_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_cmf_color_req',
            name='rs_no',
        ),
        migrations.RemoveField(
            model_name='tbl_cmf_process02',
            name='rs_no',
        ),
        migrations.RemoveField(
            model_name='tbl_dc_extruder_formula',
            name='rs_no',
        ),
        migrations.RemoveField(
            model_name='tbl_mb_extruder_formula',
            name='rs_no',
        ),
        migrations.RemoveField(
            model_name='tbl_resins_selected',
            name='rs_no',
        ),
    ]
