# Generated by Django 6.0.6 on 2026-09-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_tbl_cmf_pending_completed_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_cmf',
            name='est_qty_order',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated quantity in KG', max_digits=10, null=True),
        ),
    ]
