# Generated by Django 6.0.6 on 2026-09-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_alter_tbl_cmf_est_qty_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_cmf',
            name='est_qty_order',
            field=models.CharField(blank=True, help_text='Estimated quantity in KG/MT', max_length=100, null=True),
        ),
    ]
