# Generated by Django 6.0.6 on 2026-09-17 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_remove_tbl_cmf_color_req_rs_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_rs',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_column='approved_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rs_approved', to=settings.AUTH_USER_MODEL),
        ),
    ]
