# Generated by Django 6.0.6 on 2026-09-22 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_alter_tbl_cmf_est_qty_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_field_note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('field', models.CharField(max_length=50)),
                ('cmf_formula_no', models.ForeignKey(db_column='cmf_formula_no', on_delete=django.db.models.deletion.CASCADE, related_name='field_notes', to='main.tbl_cmf_formula')),
            ],
            options={
                'db_table': 'tbl_field_note',
                'unique_together': {('cmf_formula_no', 'field')},
            },
        ),
    ]
