# Generated by Django 6.0.6 on 2026-09-17 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_tbl_rs_approved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_rs',
            name='color_desc',
        ),
        migrations.RemoveField(
            model_name='tbl_rs',
            name='colorant_type',
        ),
        migrations.RemoveField(
            model_name='tbl_rs',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='tbl_rs',
            name='finished_product',
        ),
        migrations.RemoveField(
            model_name='tbl_rs',
            name='matching_type',
        ),
        migrations.RemoveField(
            model_name='tbl_rs',
            name='primary_color',
        ),
    ]
