# Generated by Django 6.0.6 on 2026-09-24 06:55

from django.db import migrations

def seed_data(apps, schema_editor):
    InternalColorCode = apps.get_model('main', 'tbl_internal_color_code')
    Resin = apps.get_model('main', 'tbl_resin')

    # 1. Seed tbl_internal_color_code
    color_codes = [
        {"color": "white", "code": "W"},
        {"color": "N/A", "code": "AD"},
    ]
    for item in color_codes:
        InternalColorCode.objects.get_or_create(
            code=item["code"],
            defaults={"color": item["color"]}
        )

    # 2. Seed tbl_resin
    resins = [
        {"abbreviation": "PP HOMO", "code": "P", "is_deleted": False},
        {"abbreviation": "PP BLOCK COPO", "code": "P", "is_deleted": False},
        {"abbreviation": "PP RANDOM COPO", "code": "P", "is_deleted": False},
        {"abbreviation": "PP IMPACT COPO", "code": "P", "is_deleted": False},
    ]
    for r in resins:
        Resin.objects.get_or_create(
            abbreviation=r["abbreviation"],
            code=r["code"],
            defaults={"is_deleted": r["is_deleted"]}
        )


def reverse_seed_data(apps, schema_editor):
    InternalColorCode = apps.get_model('main', 'tbl_internal_color_code')
    Resin = apps.get_model('main', 'tbl_resin')

    # Revert color codes
    InternalColorCode.objects.filter(code__in=["W", "AD"]).delete()

    # Revert resins
    Resin.objects.filter(
        abbreviation__in=[
            "PP HOMO",
            "PP BLOCK COPO",
            "PP RANDOM COPO",
            "PP IMPACT COPO",
        ]
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_alter_tbl_cmf_est_qty_order_tbl_field_note'),
    ]

    operations = [
        migrations.RunPython(seed_data, reverse_seed_data),
    ]
