# Generated by Django 6.0.6 on 2026-09-24 07:00

from django.db import migrations

def seed_access_point(apps, schema_editor):
    AccessPoint = apps.get_model('main', 'tbl_access_point')
    AccessPoint.objects.get_or_create(
        access_name="RS Records"
    )


def reverse_access_point(apps, schema_editor):
    AccessPoint = apps.get_model('main', 'tbl_access_point')
    AccessPoint.objects.filter(access_name="RS Records").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_add_color_codes_and_resins'),
    ]

    operations = [
         migrations.RunPython(seed_access_point, reverse_access_point),
    ]
