# Generated by Django 6.0.6 on 2026-09-29 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_add_rs_records_access_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_formula_resin',
            fields=[
                ('formula_resin_id', models.AutoField(primary_key=True, serialize=False)),
                ('resin', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tbl_formula_resin',
            },
        ),
        migrations.CreateModel(
            name='tbl_formula_resin_selected',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dc_no', models.ForeignKey(blank=True, db_column='dc_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tbl_dc_extruder_formula')),
                ('formula_resin_id', models.ForeignKey(db_column='formula_resin_id', on_delete=django.db.models.deletion.CASCADE, to='main.tbl_formula_resin')),
                ('mb_no', models.ForeignKey(blank=True, db_column='mb_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tbl_mb_extruder_formula')),
            ],
            options={
                'db_table': 'tbl_formula_resin_selected',
            },
        ),
    ]
