# Generated by Django 6.0.6 on 2026-09-29 01:30

from django.db import migrations

def copy_resins(apps, schema_editor):
    tbl_resin = apps.get_model('main', 'tbl_resin')  # replace 'main' with your app name if needed
    tbl_formula_resin = apps.get_model('main', 'tbl_formula_resin')

    abbreviations = (
        tbl_resin.objects
        .exclude(abbreviation__isnull=True)
        .exclude(abbreviation='')
        .values_list('abbreviation', flat=True)
        .distinct()
    )

    records = [tbl_formula_resin(resin=abbr.strip()) for abbr in abbreviations]
    tbl_formula_resin.objects.bulk_create(records, ignore_conflicts=True)

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_tbl_formula_resin_tbl_formula_resin_selected'),
    ]

    operations = [
        migrations.RunPython(copy_resins),
    ]
