# Generated by Django 6.0.6 on 2026-09-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_auto_20260929_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_feedback_details',
            name='abandoned_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_feedback_details',
            name='order_form_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tbl_feedback_details',
            name='submitted_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
