# Generated by Django 6.0.6 on 2026-09-29 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_tbl_feedback_details_abandoned_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_feedback_details',
            name='submitted_by',
            field=models.ForeignKey(blank=True, db_column='sm_no', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tbl_cmf_salesman'),
        ),
    ]
