# Generated by Django 6.0.6 on 2026-09-29 08:48

from django.db import migrations

def add_inhouse_salesman(apps, schema_editor):
    Salesman = apps.get_model('main', 'tbl_cmf_salesman')  # Replace 'main' if your app name is different
    # get_or_create checks first: if it exists, it does nothing; if not, it creates it.
    Salesman.objects.get_or_create(name='inhouse')

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_alter_tbl_feedback_details_submitted_by'),
    ]

    operations = [
        migrations.RunPython(add_inhouse_salesman, reverse_code=migrations.RunPython.noop),
    ]
