# Generated by Django 6.0.6 on 2026-10-03 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_auto_20260929_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_dc_extruder_version',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_mb_extruder_formula02',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_mb_extruder_formula02',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=16, null=True),
        ),
    ]
