# Generated by Django 6.0.6 on 2026-10-03 02:02

from django.db import migrations

def add_not_specified_specification(apps, schema_editor):
    Spec = apps.get_model('main', 'tbl_cmf_specification')
    Spec.objects.get_or_create(name='Not Specified')

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_alter_tbl_dc_extruder_version_value_and_more'),
    ]

    operations = [
        migrations.RunPython(add_not_specified_specification, reverse_code=migrations.RunPython.noop),
    ]
