# Generated by Django 6.0.6 on 2026-10-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_auto_20261003_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_feedback_details',
            name='status',
            field=models.CharField(default='waiting for result', max_length=100),
        ),
    ]
