# Generated by Django 6.0.6 on 2026-10-05 03:29

from django.db import migrations

def update_status_to_waiting(apps, schema_editor):
    # Get the model historical version using apps.get_model
    tbl_feedback_details = apps.get_model('main', 'tbl_feedback_details')
    
    # Update all rows where status is 'pending'
    tbl_feedback_details.objects.filter(status='pending').update(status='waiting for result')

def reverse_status_update(apps, schema_editor):
    # Optional: Define what happens if you ever rollback the migration
    tbl_feedback_details = apps.get_model('main', 'tbl_feedback_details')
    tbl_feedback_details.objects.filter(status='waiting for result').update(status='pending')

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_alter_tbl_feedback_details_status'),
    ]

    operations = [
        migrations.RunPython(update_status_to_waiting, reverse_status_update),
    ]
